#ifndef _INCLUDE_PT_LIB_H
#define _INCLUDE_PT_LIB_H

/* Generated with cbindgen:0.6.3 */

/* Warning: Autogenerated, DO NOT MODIFY */

#include <cstdint>
#include <cstdlib>

// provides a touch point for positron state tracking
struct PositronContext {
  int32_t state;
};

extern "C" {

// Allocate a new c-api context instance
PositronContext *pt_ctx_alloc();

// Free a c-api context instance
void pt_ctx_free(PositronContext *ctx);

// Incr and return the state of a c-api context instance
int32_t pt_ctx_incr(PositronContext *ctx);

// Peek at the state of a c-api context instance
int32_t pt_ctx_peek(PositronContext *ctx);

} // extern "C"

#endif // _INCLUDE_PT_LIB_H
