extern crate cbindgen;

use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_include_guard("_INCLUDE_PT_LIB_H")
        .with_autogen_warning("/* Warning: Autogenerated, DO NOT MODIFY */")
        .with_include_version(true)
        .with_language(cbindgen::Language::Cxx)
        .generate()
        .expect("Failed to generate c header")
        .write_to_file("include/ptlib.h");
}
